# Dataset configuration
data_path: ./dataset
field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
LABEL_FIELD: label
TIME_FIELD: timestamp

load_col:
  inter: ["user_id", "item_id", "label", "timestamp"]

# Model arguments
model_args:
  EASE:
    reg_weight: 500  # Regularization weight
  LightGCN:
    embedding_size: 64  # 임베딩 크기
    n_layers: 3         # Graph propagation layers
    reg_weight: 1e-4    # Regularization weight



# Training configuration
# epochs: 3               # 3번에 45분 정도, EASE는 선형 모델로 한 번의 학습으로 충분
train_batch_size: 2048
learning_rate: 0.001  

# Evaluation configuration
eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}
  group_by: user
  order: RO
  mode: {'valid': 'full', 'test': 'full'}
  save_result: True
  disable_tqdm: True

checkpoint_dir: ./saved
checkpoint_file: "{model_name}-{timestamp}.pth"

metrics: ['Recall', 'Precision', 'MAP', 'NDCG']
topk: [5, 10]
valid_metric: Recall@10
