# config/config_baseline.yaml

seed: 42                                        # 시드 고정
device: "cuda"
wandb_project: "movie"                          # wandb 프로젝트 이름
data_path: "~/movie/data/train/"
output_path: "output/"

model_args:                                     # model 파라미터
    EASE:
        reg_lambda: 500
    EASER:
        reg_lambda: 500
        smoothing: 0.001
    MultiVAE:
        input_dim: 6807